services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  api-service:
    build:
      context: .
      dockerfile: apps/api-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  engine-service:
    build:
      context: .
      dockerfile: apps/engine-service/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  price-poller-service:
    build:
      context: .
      dockerfile: apps/price-poller-service/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis